language: node_js
sudo: true
node_js:
- '10'
install:
- npm install
- npm run build
script:
- npm run lint
- npm run test
before_install:
- openssl aes-256-cbc -K $encrypted_914e19770d5d_key -iv $encrypted_914e19770d5d_iv
  -in src/test/config.ts.enc -out src/test/config.ts -d
after_success: 'npm run coverage'
